[package]
name = "summer-boot"
version = "0.1.0"
rust-version = "1.60.0"
edition = "2021"
description = "summer boot core"
authors = [
    "James Zow <Jameszow@163.com>"
]
license = "Apache-2.0"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"

socket2 = "0.4.4"